### ISSUE TITLE
Field names with underscore is not visible properly in the columns ( hide / show ) section.

### ISSUE THREAD

**Issue by chintanshahts** [rinku-samanta-ts/ts-fe-boilerplate#7]
![image](https://github.com/user-attachments/assets/141777fd-aae4-41d4-9747-e8473155558c)

**Example**

`is_active`

Its coming like 

`IS_ACTIVE`

**`Note`** :: field name can be in camelCase as well.

**Comment by akshay-pathak-techno** [comment]
@chintanshahts in some case we need the total different name to display than we specify in accessorKey  so we can add facility to user to override the custom title.
cc: @rinku-samanta-ts
